#!/bin/bash
set -e

: ${KALABOX_UID:='1000'}
: ${KALABOX_GROUP:='staff'}

# Apache gets grumpy about PID files pre-existing
rm -f /var/run/apache2/apache2.pid

# Do this so our mounted VB volumes work
echo "Remapping apache permissions for VB sharing compat..."
usermod -u $KALABOX_UID www-data
usermod -G $KALABOX_GID www-data
chown -Rf www-data:www-data /var/www/html
chown -Rf www-data:www-data /media

# Create symlink here on wordpress because of how
# wordpress is extracted on runtime instead of on build
if [ $FRAMEWORK == "wordpress" ] && [ ! -f "/var/www/html/wp-content/uploads" ]; then
  echo "Symlinking WP uploads to /media"
  ln -nsf /media /var/www/html/wp-content/uploads
fi

exec apache2 -DFOREGROUND
